### PR TITLE
Added a proposal for a new icon and logo

### PR DESCRIPTION
**Pull request by rmvdesign**
# Pull request

* [ x ] Have you followed the guidelines in our Contributing document?
* [ x ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:
1. [ x ] Did you lint your code locally before submission?
2. [  ] Did you test your feature thoroughly to ensure there are no bugs?
3. [  ] Does your feature introduce breaking changes?

### Changes to Core Features:

* [ x ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Please describe your changes
This PR adds assets for a new logo and icon I designed for Kanri, inspired by classic macOS design, but with added Windows/Linux variants and a simple version to be used in the sidebar. The logo is not implemented, but rather there as a suggestion for the maintainer.

### Additional context
Love from Threads :) -1612elphi

### CODE REVIEW

**Comment by trobonox** [comment]
Thanks for the logo proposal, really appreciate it. I like the idea and think the macOS version looks pretty nice. Will have to see how the logo would look inside the app and other branding to be able to conclude if I like it or if I can use it as a starting point for creating my own version.

Thanks again and will let you know what my final decision will be :)

**Comment by trobonox** [comment]
Just tried it out in some branding and inside the actual app, and it feels a little off... 
Unfortunately I'm not able to pinpoint what exactly is wrong and I don't want to bother you with more work, so do you mind providing me the file where you created the logos so I can make some edits myself? 
If I end up using your idea as a "template", I'll make sure to credit you.

**Comment by rmvdesign** [comment]
Sure! This should be the link: [Figma](https://www.figma.com/file/Mzvlqi1wh5dOzDR6DRssG6?node-id=0:1&locale=en&type=design)

**Comment by trobonox** [comment]
Thanks! Do you mind closing the PR since the final files will be different anyway?

**Comment by trobonox** [comment]
Thanks!

**Pull request closed without merging**
